name: Push EspNowNetworkHost to Espressif Component Service
on:
  release:
    types: [created]
jobs:
  build_examples_for_verification:
    uses: ./.github/workflows/espidf.yaml
    with:
      target_path: "examples/espidf/host"

  upload_components:
    runs-on: ubuntu-latest
    needs: [build_examples_for_verification]
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Remove arduino examples and library related files
        run: rm -rf examples/arduino library.json library.properties

      - name: Remove github actions
        run: rm -rf .github

      - name: Upload EspNowNetworkHost to component registry
        uses: espressif/upload-components-ci-action/@v1
        with:
          name: "EspNowNetworkHost"
          namespace: "johboh"
          api_token: ${{ secrets.ESP_IDF_COMPONENT_API_TOKEN }}
